[5.4] update apps repo urls (#197)
* updated for gitlab urls

* Update config.yml

* Update app.config.yml

* fixed the branch on app_urls

* let gt_fetch_as be overridden

* fixed missing .git

* https -> git per dev pleading to changing the default

CI still will use https since i guess it doesn't have ssh permission to
access other repos!

* adding gitlab cli (glab) to kgit

* test ci

---------

Co-authored-by: Hesaam Farhang <hesaam@2600hz.com>

diff --git a/kgit b/kgit
--- a/kgit
+++ b/kgit
@@ -95,6 +95,7 @@ Usage:
         git        Runs git command
         gh         Runs gh command (https://cli.github.com)
         hub        Runs hub command (https://github.com/github/hub)
+        glab       Runs GitLab CLI command (https://docs.gitlab.com/editor_extensions/gitlab_cli)
 
 Example:
 
@@ -113,7 +114,7 @@ Options:
     -exit-on-error                       exit if command returns exit other than 0
     -kchanged                            loop over working directories and prints the name of files which are
                                              different than "$BASE_BRANCH". "master" is the default BASE_BRANCH
-                                         this does not run git/hub/gh commands
+                                         this does not run git/hub/gh/glab commands
     -get-root                            print path to Kazoo source directory and exit
     -q                                   be quiet, but still print error messages
     -qq                                  be more quiet, also do not print errors
@@ -209,6 +210,13 @@ while [ $# -gt 0 ]; do
             ;;
         gh)
             _action="gh"
+            # explicit end of options
+            explicit_opts_end=1
+            shift
+            break
+            ;;
+        glab)
+            _action="glab"
             # explicit end of options
             explicit_opts_end=1
             shift
@@ -341,6 +349,9 @@ check_action() {
             git)
                 echo "Please install git version 2+ using your distro package manager." >&2
                 ;;
+            glab)
+                echo "Please follow instructions in https://docs.gitlab.com/editor_extensions/gitlab_cli/#install-the-cli to install it." >&2
+                ;;
             hub)
                 echo "Please follow instructions in https://github.com/github/hub#installation to install it." >&2
                 ;;
@@ -404,6 +415,7 @@ run_git() {
 
 loop_wait_gh() {
     local counter=1
+    # may need update this if gitlab rate limit `mr` api calls
     if [[ "$@" =~ "pr create" ]] || [[ "$@" =~ "issue create" ]]; then
         echo -n "Waiting 60s on stupid GitHub to avoid GraphQL limit on creation"
         while [ $counter -le 60 ]; do
@@ -447,7 +459,7 @@ run_action() {
     done
 }
 
-# let git/hub/gh fail, we can stop if user requested -exit-non-error
+# let git/hub/gh/glab fail, we can stop if user requested -exit-non-error
 set +e
 
 case "$_action" in
